config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'pages#home'
  get 'about' => 'pages#about' #this creates the about_path
  get 'contact' => 'pages#contact'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-default" role="navigation">
  <div class=container
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to "Bowline Investments", root_path, class: "navbar-brand" %>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "About", about_path %></li> 
      <li><%= link_to "Contact Us", contact_path %></li>
    <% if user_signed_in? %>
      <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
    <% else %>
      <li><%= link_to "Sign In", new_user_session_path %></li>
    <% end %>
    </ul>
  </div><!-- /.navbar-collapse -->
</div> <!-- container --> 
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bowline Investments</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
	<%= render 'layouts/header' %>
<div class="container">
	<% flash.each do |name, msg| %>
		<%= content_tag(:div, msg, class: "alert alert-info") %>
	<% end %>
          <%= yield %>          
     </div>

</body>
</html>

app/views/pages/about.html.erb
<div class="jumbotron">

	<h1>About Bowline</h1>
	<p>If you would like to know more about our approach and services, please email <a href="mailto:info@frontshore.com?subject=Bowline Enquiry">Bowline</a> here.</p> 
</div>

app/views/pages/contact.html.erb
<div class="jumbotron">
	<h1>Contact Bowline</h1>
		<p>If you would like to know more about our approach and services, please email <a href="mailto:info@frontshore.com?subject=Bowline Enquiry">Bowline</a> here.</p> 
	</div>

app/views/pages/home.html.erb
<div class="jumbotron center">

	<h1>Bowline Investments</h1>
	<h2>Private Cayman Fund Manager</h2>

	<p>Bowline is an Exempt fund manager incorporated in the Cayman Islands.</p>

	<p>If you would like to know more about our approach and services, please email <a href="mailto:info@frontshore.com?subject=Bowline Enquiry">Bowline</a> here.</p> 

	<% if user_signed_in? %>
	 <!-- do something -->

	 <% else %>

		<p>Click to 
			<%= link_to "Log in", new_user_session_path, class: "btn btn-default btn-lg" %></p>

	<% end -%>
</div>